services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=ejemploplay_db'
      - 'POSTGRES_PASSWORD=changeMe2'
      - 'POSTGRES_USER=william'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
